layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: fernandobastos.90
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: fernando-h-m-bastos-58aab168
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://isocpp.org/
    image_url: assets/img/cpp.jpg

  - name: Info Sec
    web_url: https://www.reddit.com/r/netsec
    image_url: assets/img/cybersec.png

  - name: Malware Analysis
    web_url: https://en.wikipedia.org/wiki/Malware_analysis
    image_url: assets/img/bug.png

  - name: Swift
    web_url: https://swift.org/
    image_url: assets/img/swift.png

